#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

chmod +x /etc/init.d/d1-index-task-generator
chmod +x /etc/init.d/d1-index-task-processor

update-rc.d d1-index-task-generator defaults 99
update-rc.d d1-index-task-processor defaults 99

if [ ! -d "/etc/dataone/index" ]; then
  mkdir /etc/dataone/index
fi

#provide context properties files for postgres, log4j, solr location
cp /usr/share/dataone-cn-index/debian/log4j-generator.properties /etc/dataone/index/log4j-generator.properties
cp /usr/share/dataone-cn-index/debian/log4j-processor.properties /etc/dataone/index/log4j-processor.properties
cp /usr/share/dataone-cn-index/debian/jdbc.properties /etc/dataone/index/jdbc.properties
cp /usr/share/dataone-cn-index/debian/solr.properties /etc/dataone/index/solr.properties
cp -rf /usr/share/dataone-cn-index/debian/index-generation-context /etc/dataone/index/

chown -R tomcat6.tomcat6 /etc/dataone/index

cp /usr/share/dataone-cn-index/d1_index_task_generator_daemon.jar /usr/share/java
cp /usr/share/dataone-cn-index/d1_index_task_processor_daemon.jar /usr/share/java
cp /usr/share/dataone-cn-index/d1_index_build_tool.jar /usr/share/java

chown -R tomcat6.tomcat6 /usr/share/java/d1_index_task_generator_daemon.jar
chown -R tomcat6.tomcat6 /usr/share/java/d1_index_task_processor_daemon.jar
chown -R tomcat6.tomcat6 /usr/share/java/d1_index_build_tool.jar

if [ ! -d "/var/log/dataone/index" ]; then
  mkdir  /var/log/dataone/index
fi
chown tomcat6.tomcat6 /var/log/dataone/index


###############################################################################
# Configure Postgres
###############################################################################
PG=postgresql-8.4
PG_CONF=/etc/postgresql/8.4/main
PG_USER=postgres

INDEX_DB=d1-index-queue
INDEX_DB_USER=indexer
INDEX_DB_PASS=indexer

## modify pg_hba.conf
PG_HBA_IS_MODIFIED=`grep "${INDEX_DB} ${INDEX_DB_USER}" ${PG_CONF}/pg_hba.conf`
if [ "${PG_HBA_IS_MODIFIED}" == "" ]
then
  echo "backing up ${PG_CONF}/pg_hba.conf to ${PG_CONF}/pg_hba.conf.bak.index"
  cp ${PG_CONF}/pg_hba.conf ${PG_CONF}/pg_hba.conf.bak.index
  chown ${PG_USER} ${PG_CONF}/pg_hba.conf
  chgrp ${PG_USER} ${PG_CONF}/pg_hba.conf

  echo "appending 'host ${INDEX_DB} ${INDEX_DB_USER} 127.0.0.1 255.255.255.255 password' to ${PG_CONF}/pg_hba.conf"
  echo "host ${INDEX_DB} ${INDEX_DB_USER} 127.0.0.1 255.255.255.255 password" >> ${PG_CONF}/pg_hba.conf
fi

## create index task schema and user
echo "Creating index task database schema"
su ${PG_USER} -c "createdb ${INDEX_DB}"

echo "Creating index task db user - indexer" 
su ${PG_USER} -c "psql -c \"CREATE USER ${INDEX_DB_USER} WITH UNENCRYPTED PASSWORD '${INDEX_DB_PASS}'\""


## Restart the postgres db
echo "Restarting postgres database"
/etc/init.d/${PG} restart
######################################################


/etc/init.d/tomcat6 stop

if [ ! -d "/etc/dataone/index/solr" ]; then
  mkdir  /etc/dataone/index/solr
fi

if [ -f "/etc/dataone/index/solr/schema.properties" ]; then
  ORIGINAL_SCHEMA_FILE=`awk -F"=" '/schema-file/{ print $2 }' /etc/dataone/index/solr/schema.properties`
  CORE_NAME=`awk -F"=" '/core-name/{ print $2 }' /etc/dataone/index/solr/schema.properties`
else
  CORE_NAME="d1-cn-index"
fi

if [ -f "/usr/share/dataone-cn-index/schema.properties" ]; then
  NEW_SCHEMA_FILE=`awk -F"=" '/schema-file/{ print $2 }' /usr/share/dataone-cn-index/schema.properties`
else
  NEW_SCHEMA_FILE="index-solr-schema-v1.xml"
fi

cp /usr/share/dataone-cn-index/$NEW_SCHEMA_FILE /etc/dataone/index/solr/
cp /usr/share/dataone-cn-index/debian/d1search.xsl /etc/dataone/index/solr/
ln -fs /etc/dataone/index/solr/d1search.xsl /usr/share/solr/$CORE_NAME/conf/xslt/d1search.xsl

if [ ! -f "/etc/dataone/index/solr/schema.properties" ]; then
	# fresh install
  ln -fs /etc/dataone/index/solr/$NEW_SCHEMA_FILE /etc/dataone/index/schema-current.xml
  ln -fs /etc/dataone/index/solr/$NEW_SCHEMA_FILE /usr/share/solr/$CORE_NAME/conf/schema.xml
elif [ "$ORIGINAL_SCHEMA_FILE" != "$NEW_SCHEMA_FILE" ]; then
  # upgrade
  if [ -z "$ORIGINAL_SCHEMA_FILE" ]; then
    # first upgrade to versioned schemas
    ln -fs /etc/dataone/index/solr/$NEW_SCHEMA_FILE /etc/dataone/index/schema-current.xml
  fi
  SCHEMA_UPDATE="true"
fi

cp /usr/share/dataone-cn-index/schema.properties /etc/dataone/index/solr/schema.properties

##########################
chown -R tomcat6.tomcat6 /usr/share/solr/d1-cn-index/
chown -R tomcat6.tomcat6 /etc/dataone/index/solr

/etc/init.d/tomcat6 start

######### Finished! inform user how to start daemons
echo ""
echo "CN Search Index has finished installing. "
echo "To build or re-build Solr Index with /usr/share/dataone-cn-index/d1_index_build_tool.jar " 
echo "while index task processor daemon is not running. "
echo "You can do this using /usr/share/dataone-cn-index/scripts/index-tool.sh for example."
echo ""
echo "Start Index Task Generator with /etc/init.d/d1-index-task-generator start"
echo "Start Index Task Processor with /etc/init.d/d1-index-task-processor start"

if [ -n "$SCHEMA_UPDATE" ]; then
  echo ""
  echo "The search index schema has been updated. "
  echo "Before starting the index-task-processsor, "
  echo "the search index must be migrated."
  echo "Use: /usr/share/dataone-cn-index/scripts/migrate-search-index.sh"
fi

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html
