#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

chmod +x /etc/init.d/d1-index-task-generator
chmod +x /etc/init.d/d1-index-task-processor

if [ ! -d "/etc/dataone/index" ]; then
  mkdir /etc/dataone/index
  FRESH_INSTALL="true"
fi

if [ ! -d "/etc/dataone/index/solr" ]; then
  mkdir  /etc/dataone/index/solr
fi

#provide context properties files for postgres, log4j, solr location
cp /usr/share/dataone-cn-index/debian/d1client.properties /etc/dataone/index/d1client.properties
cp /usr/share/dataone-cn-index/debian/log4j-generator.properties /etc/dataone/index/log4j-generator.properties
cp /usr/share/dataone-cn-index/debian/log4j-processor.properties /etc/dataone/index/log4j-processor.properties
cp /usr/share/dataone-cn-index/debian/jdbc.properties /etc/dataone/index/jdbc.properties
cp /usr/share/dataone-cn-index/debian/solr.properties /etc/dataone/index/solr.properties
cp /usr/share/dataone-cn-index/queryFieldDescriptions.properties /etc/dataone/index/solr/queryFieldDescriptions.properties
cp -rf /usr/share/dataone-cn-index/debian/index-generation-context /etc/dataone/index/


# source the debconf library
if [ -e "/usr/share/debconf/confmodule" ]; then
    . /usr/share/debconf/confmodule
else
    echo "debconf must be installed. Exiting."
    exit 1
fi

db_get dataone-cn-os-core/cn.hostname
HOSTNAME=$RET
if [ "$HOSTNAME" != "" ]
then
  sed -i.bak  's/SERVER_NAME/'${HOSTNAME}'/' /etc/dataone/index/d1client.properties
else
  echo "HOSTNAME can not be set in /etc/dataone/d1client.properties"
fi


chown -R tomcat7:tomcat7 /etc/dataone/index

cp /usr/share/dataone-cn-index/d1_index_task_generator_daemon.jar /usr/share/java
cp /usr/share/dataone-cn-index/d1_index_task_processor_daemon.jar /usr/share/java
cp /usr/share/dataone-cn-index/d1_index_build_tool.jar /usr/share/java

chown -R tomcat7:tomcat7 /usr/share/java/d1_index_task_generator_daemon.jar
chown -R tomcat7:tomcat7 /usr/share/java/d1_index_task_processor_daemon.jar
chown -R tomcat7:tomcat7 /usr/share/java/d1_index_build_tool.jar

if [ ! -d "/var/log/dataone/index" ]; then
  mkdir  /var/log/dataone/index
fi
chown -R tomcat7:tomcat7 /var/log/dataone/index


###############################################################################
# Configure Postgres
###############################################################################
PG=postgresql
PG_CONF=/etc/postgresql/9.1/main
PG_USER=postgres

INDEX_DB=d1-index-queue
INDEX_DB_USER=indexer
INDEX_DB_PASS=indexer

## modify pg_hba.conf
PG_HBA_IS_MODIFIED=`grep "${INDEX_DB} ${INDEX_DB_USER}" ${PG_CONF}/pg_hba.conf`
if [ "${PG_HBA_IS_MODIFIED}" == "" ]
then
  echo "backing up ${PG_CONF}/pg_hba.conf to ${PG_CONF}/pg_hba.conf.bak.index"
  cp ${PG_CONF}/pg_hba.conf ${PG_CONF}/pg_hba.conf.bak.index
  chown ${PG_USER} ${PG_CONF}/pg_hba.conf
  chgrp ${PG_USER} ${PG_CONF}/pg_hba.conf

  echo "appending 'host ${INDEX_DB} ${INDEX_DB_USER} 127.0.0.1 255.255.255.255 password' to ${PG_CONF}/pg_hba.conf"
  echo "host ${INDEX_DB} ${INDEX_DB_USER} 127.0.0.1 255.255.255.255 password" >> ${PG_CONF}/pg_hba.conf
fi

## create index task schema and user
echo "Creating index task database schema"
su ${PG_USER} -c "createdb ${INDEX_DB}"

echo "Creating index task db user - indexer" 
su ${PG_USER} -c "psql -c \"CREATE USER ${INDEX_DB_USER} WITH UNENCRYPTED PASSWORD '${INDEX_DB_PASS}'\""


## Restart the postgres db
echo "Restarting postgres database"
/etc/init.d/${PG} restart
######################################################


/etc/init.d/tomcat7 stop

if [ -f "/etc/dataone/index/solr/schema.properties" ]; then
  ORIGINAL_SCHEMA_FILE=`awk -F"=" '/schema-file/{ print $2 }' /etc/dataone/index/solr/schema.properties`
  CORE_NAME=`awk -F"=" '/core-name/{ print $2 }' /etc/dataone/index/solr/schema.properties`
else
	#default core name
  CORE_NAME="d1-cn-index"
fi

if [ -f "/usr/share/dataone-cn-index/schema.properties" ]; then
  NEW_SCHEMA_FILE=`awk -F"=" '/schema-file/{ print $2 }' /usr/share/dataone-cn-index/schema.properties`
else
	#default schema
  NEW_SCHEMA_FILE="index-solr-schema-v1_1.xml"
fi

#if [ ! -f "/etc/dataone/index/solr/$NEW_SCHEMA_FILE" ]; then
## ALWAYS copy schema file
#fi
cp /usr/share/dataone-cn-index/$NEW_SCHEMA_FILE /etc/dataone/index/solr/
cp /usr/share/dataone-cn-index/index-solrconfig.xml /usr/share/solr/d1-cn-index/conf/solrconfig.xml

cp /usr/share/dataone-cn-index/debian/d1search.xsl /etc/dataone/index/solr/

if [ -d "/usr/share/solr/$CORE_NAME" ]; then
  ln -fs /etc/dataone/index/solr/d1search.xsl /usr/share/solr/$CORE_NAME/conf/xslt/d1search.xsl
fi

if [ -d "/usr/share/solr/d1-cn-index" ]; then
  ln -fs /etc/dataone/index/solr/d1search.xsl /usr/share/solr/d1-cn-index/conf/xslt/d1search.xsl
fi

if [ -n "$FRESH_INSTALL" ]; then
  ln -fs /etc/dataone/index/solr/$NEW_SCHEMA_FILE /etc/dataone/index/schema-current.xml
  ln -fs /etc/dataone/index/solr/$NEW_SCHEMA_FILE /usr/share/solr/$CORE_NAME/conf/schema.xml
elif [ "$ORIGINAL_SCHEMA_FILE" != "$NEW_SCHEMA_FILE" ]; then
  # upgrade
  SCHEMA_UPDATE="true"
fi

if [ -n "$FRESH_INSTALL" ]; then
  cp /usr/share/dataone-cn-index/schema.properties /etc/dataone/index/solr/schema.properties
else
  cp /usr/share/dataone-cn-index/schema.properties /etc/dataone/index/solr/schema-next.properties
fi

##########################
chown -R tomcat7:tomcat7 /usr/share/solr/d1-cn-index/
chown -R tomcat7:tomcat7 /etc/dataone/index/solr

/etc/init.d/tomcat7 start

######### Finished! inform user how to start daemons
echo ""
echo "CN Search Index has finished installing. "
echo "To build or re-build Solr Index with /usr/share/dataone-cn-index/d1_index_build_tool.jar " 
echo "while index task processor daemon is not running. "
echo "You can do this using /usr/share/dataone-cn-index/scripts/index-tool.sh for example."
echo ""
echo "Start Index Task Generator with /etc/init.d/d1-index-task-generator start"
echo "Start Index Task Processor with /etc/init.d/d1-index-task-processor start"

if [ -n "$SCHEMA_UPDATE" ]; then
  echo ""
  echo "The search index schema has been updated. "
  echo "Before starting the index-task-processsor, "
  echo "the search index must be migrated."
  echo "Use: /usr/share/dataone-cn-index/scripts/migrate-search-index.sh"
fi


#install for solr4 usage
SOLR4_INSTALL_DIR=/var/solr/

if [ -e ${SOLR4_INSTALL_DIR} ]; then
  echo 'solr4 installed.  copying solr.properties for solr4...'
  cp /usr/share/dataone-cn-index/debian/solr4.properties /etc/dataone/index/solr.properties
fi

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html
 
db_stop 
 
exit 0
